### ISSUE TITLE
MPH auto switch fails on XMR

### ISSUE THREAD

**Issue by snippy62** [papampi/nvOC_by_fullzero#137]
i cant figure it out still not working to me i looks like it all going good check the price and then launches in my case XMR and says launching in glake but the mesage there is 

m1@m1-desktop:$ tail -n 0 -f /home/m1/NVOC/Testing1/nvoc_logs/screenlog.0
tail: cannot open '/home/m1/NVOC/Testing1/nvoc_logs/screenlog.0' for reading: No such file or directory
tail: no files remaining

to me the error is when the MPH switch is launching the miner but im just a guy trying to learn and cant find the error i did a fresh install with latest pull and still would not work

**Comment by LuKePicci** [comment]
The problem is that the xmr miner has changed from previous release to support criptonightv7, as I pointed out in #133 there is also the CNheavy miner which is binded to xmrig, but I don't know if the current cryptonightv7 miner, which is xmr-stack, is compatible with CNheavy also.

BTW this should be a problem with cryptonight only (and xmr of course).

The error of screenlog not found is probably due to the miner not starting and not generating any log.

**Comment by snippy62** [comment]
is it posable to remove one algo from the MPH script ...... i tryed to remove it from the mph_conf.json but it just recreats the algo inside the file

**Comment by LuKePicci** [comment]
You can't right know, but if I got a bit of time I can try moving those json templates outside of 3main to allow using customized json settings when they exists.

I just pushed a corrective commit for XMR in mph_switch in #136, but I can't test it so we will wait for your feedback.

**Comment by snippy62** [comment]
Still cant get it to launch it is somthing to do with the end of the script the first is a sample of just runnung a coin in this cash MPH_EQUIHASH but when i run the auto switcher after it says launching miner it starts the loop again and i cant see it evan try to launch the mining program is there a debug mode ware i can see the complete output of what is happening ? if not that would be a cool and handy 

(Switcher Output)
gamecredits (Scrypt): -0.00015112 BTC/day (-0.96 USD/day)
startcoin (X11): -0.00015176 BTC/day (-0.97 USD/day)
sexcoin (Scrypt): -0.00015176 BTC/day (-0.97 USD/day)

mining process in Guake Tab

(Auto switch tab in my guake tab )

m1@m1-desktop:$ tail -n 0 -f /home/m1/NVOC/Test2/nvoc_logs/screenlog.0
tail: cannot open '/home/m1/NVOC/Test2/nvoc_logs/screenlog.0' for reading: No such file or directory
tail: no files remaining
m1@m1-desktop:$ 


therre is no file in that location by that name
LAUNCHING:  MINER TEMPCONTROL

process in screen temp, guake terminal Tab (f12), 'nvOC temp-log'
12496 pts/22   S+     0:00 tail -n 0 -f /home/m1/NVOC/Test2/nvoc_logs/tempcontrol-screenlog.0

LAUNCHING:  WTM PROFIT CHECK 

Auto Start Miner Set to YES

Sun Jul 15 17:15:00 MST 2018 - Miner is running, 3main killing miner

LAUNCHING:  MINER
    
    
    SCREEN -c /home/m1/NVOC/Test2/screenrc-miner -dmSL miner /home/m1/NVOC/Test2/miners/dstm/latest/zm_miner --server us-east.equihash-hub.miningpoolhub.com --user Snippy6.Snippy6 --port 17023 --pass x --time
    
Miner output: ./nvOC miner-log
    
    
    SCREEN -c /home/m1/NVOC/Test2/screenrc-miner -dmSL miner /home/m1/NVOC/Test2/miners/dstm/latest/zm_miner --server us-east.equihash-hub.miningpoolhub.com --user Snippy6.Snippy6 --port 17023 --pass x --time
2018-07-15 05:15:04 PM|#  zm 0.6.1
2018-07-15 05:15:04 PM|#  GPU0 + GeForce GTX 1060 3GB     MB: 3011  PCI: 1:0
2018-07-15 05:15:04 PM|#  GPU1 + GeForce GTX 960          MB: 2002  PCI: 3:0

so as u can see its like my miner dose not even try to open after it determins what coin to mine

**Comment by LuKePicci** [comment]
Try launching yourself the miner from the command line to see what's going wrong using the command line you see from the log:

`/home/m1/NVOC/Test2/miners/dstm/latest/zm_miner --server us-east.equihash-hub.miningpoolhub.com --user Snippy6.Snippy6 --port 17023 --pass x --time`

**Comment by snippy62** [comment]
OMG i think i got it so i ran 

nvOC report and got this 
      Report generator v0019-2.1.0012 by leenoox      


[code]

Software info:
Report ver    :  v0019-2.1.0012
nvOC path     :  /home/m1/NVOC/mining
nvOC (1bash)  :  nvOC v0019-2.1 - Community Release
nvOC (3main)  :  nvOC v0019-2.1 - Community Release   
1bash ver     :  v0019-2.1.0031
3main ver     :  v0019-2.1.0024                  
5watchdog ver :  v0019-2.1.020   
6tempcontrol v:  v0019-2.1.0006   
wtm switch ver:  v0019-2.1.0022   
Kernel        :  4.4.0-130-generic
OS            :  Ubuntu 16.04.4 LTS
System        :  (gcc 5.4.0 (Ubuntu 5.4.0-6ubuntu1~16.04.9)
nvidia driver :  390.67

Hardware info:
Motherboard   :  Gateway DX4840  
BIOS ver.     :  P01-A4         02/15/2011
CPU Model     :  Core(TM) i3 CPU         550  @ 3.20GHz
CPU Cores     :  4 (Cores + Threads)
Mem Total     :         3971396 kB
Mem Free      :          941848 kB
Swap Total    :               0 kB
Swap Free     :               0 kB
Ethernet      :  Realtek RTL8111/8168/8411 PCI Express Gigabit Ethernet Controller (rev 06)

CUDA SDK version
nvcc path     : /usr/local/cuda-8.0/bin/nvcc
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2016 NVIDIA Corporation
Built on Tue_Jan_10_13:22:03_CST_2017
Cuda compilation tools, release 8.0, V8.0.61

nvoc.service systemd's log
● nvoc.service - nvOC Service
   Loaded: loaded (/etc/systemd/system/nvoc.service; static; vendor preset: enabled)
   Active: inactive (dead)

HDD and Partion info:
NAME     SIZE FSTYPE TYPE ROTA HOTPLUG TRAN   VENDOR   MODEL             REV MOUNTPOINT
sda    931.5G        disk    1       0 sata   ATA      TOSHIBA MQ01ABD1 1Q   
├─sda1     9M vfat   part    1       0                                       
└─sda2 931.5G ext4   part    1       0                                       /

VGA info:
01:00.0 VGA compatible controller: NVIDIA Corporation Device 1c02 (rev a1)
03:00.0 VGA compatible controller: NVIDIA Corporation GM206 [GeForce GTX 960] (rev a1)

Local git branch and submodules status:
## release...origin/release
 M 1bash.template
 0892f996d13b17738325880af704a60cd7b4567f miners (remotes/origin/19-2.1)
## HEAD (no branch)
 cd6fab68823e247bb84dd1fa0448d5f75ec4917d ANXccminer/src (heads/master)
 aafe2d19b6d9eb07d942d70ced3049e9aed1c241 ASccminer/src (1.5.3-tpruvot-81-gaafe2d1)
 31865e0b846ad98e2ce99aeb9b28bb51d3be22db KTccminer-cryptonight/src (2.06)
 c5ab73837c8024f1e6b8fe7ad46e6881fb8366e6 KTccminer/src (1.4.6-tpruvot-1293-gc5ab738)
 7d41d49b92db27b9ab80270adaa92f6b06d1ef78 KXccminer/src (0.1)
 78dad7dd659eae72a07d2448de62b1946c1f2b41 MSFTccminer/src (2.2.5-rvn)
 8affcb9cd09edd917d33c1ed450f23400f571bdb NAccminer/src (v2.2-mod-r2)
 9e86bdd24ed7911b698f1d0ef61a4028fcbd13c5 SPccminer/src (1.5.81)
 c800f1a803e1b2074ed2a7c15023c096d0772048 SUPRminer/src (1.5)
 a81ab0f7a557a12a21d716dd03537bc8633fd176 TPccminer/src (2.2.5-tpruvot)
 bfd1c002f98f2d63f2174618838afc28cf4ffffe cpuOPT/src (v3.8.8.1)
 48b170a5828256600ca71e66d4c114af4e114236 vertminer/src (v1.0-beta.2)
 c0ab1734332d6472225d8ac7394f6fcba71aabc9 xmr-stak/src (2.4.4)

1bash settings:
1bash version .............: v0019-2.1.0031
LOCAL or REMOTE ...........: LOCAL
TEAMVIEWER started ........: YES
SSH daemon started ........: NO
SLOW_USB_KEY_MODE .........: NO
SRR .......................: NO

Watchdog ..................: YES
SYSRQ Reboot ..............: NO
Watchdog Cycle ............: 15
GPU Utilization Threshold .: 70
Alternate Pool ............: NO

Temp Control ..............: YES
MANUAL_FAN ................: NO
TARGET_TEMP ...............: 65
__FAN_ADJUST ..............: 5
POWER_ADJUST ..............: 5
ALLOWED_TEMP_DIFF .........: 2
RESTORE_POWER_LIMIT .......: 85
MINIMAL_FAN_SPEED .........: 50
MAXIMAL_FAN_SPEED .........: 95

CLEAR_LOGS_ON_BOOT ........: NO
AUTO_UPDATE ...............: STABLE
AUTO_REBOOT ...............: NO
_Parallax_MODE (upPaste)...: NO

TELEGRAM_MESSAGES .: NO
TELEGRAM_ALERTS ...: NO

HEADLESS MODE:.............: NO
GPUPowerMizerMode_Adjust...: NO
ETH Pill ..................: NO

POWERLIMIT MODE ...........: GLOBAL
Power Limit WATTS .........: 75
OVERCLOCK MODE ............: GLOBAL
Memory Overclock ..........: 100
Core Overclock ............: 100

GLOBAL WORKERNAME .........: YES
AUTO WORKERNAME ...........: CUSTOM
WORKERNAME ................: Snippy6
plusCPU ...................: NO

COIN ......................: 
ALGO ......................: CRYPTONIGHTHEAVY
MINER .....................: xmr-stak
ZPOOLPASS .................: hidden_pass...,
WORKER ................:
ADDRESS ...............: ...
POOL ..................:
PORT ..................:
CRYPTONIGHTHEAVY INTENSITY ..........: 0

[/code]


WORK IN PROGRESS! Report script (beta release)

and this is my mph_conf.json 



  "output_dir": "/home/m1/NVOC/mining",
  "user_name": "Snippy6",
  "miner_name": "Snippy6",
  "card_type": "nvidia",
  "currency": "USD",
  "pwrcost": 0.10,
  "min_profit": 0.0,
  "miners":
  {
    "Blake-Vanilla":
    {
      "bin": "/home/m1/NVOC/mining/miners/SPccminer/ccminer -a vanilla -o stratum+tcp://{HOST}:{PORT} -u {NAME}.{MINER} -p x",
      "power_limit": 100, "gpu_oc": 100, "mem_oc": 100, "fan": 0,
      "speed": 12.3, "power": 0.389
    },
    "Cryptonight-Monero":
    {
      "bin": "/home/m1/NVOC/mining/miners/xmr-stak/xmr-stak_miner --currency monero7 --noCPU --noAMD -o {HOST}:{PORT} -u {NAME}.{MINER} -p x -i 0",
      "power_limit": 100, "gpu_oc": 100, "mem_oc": 100, "fan": 0,
      "speed": 0.000002, "power": 0.325
    },
    "Equihash":
    {
      "bin": "/home/m1/NVOC/mining/miners/ewbf/3_4/miner --eexit 3 --fee 0 --pec --server {HOST} --user {NAME}.{MINER} --pass z --port {PORT}",
      "power_limit": 100, "gpu_oc": 100, "mem_oc": 100, "fan": 0,
      "speed": 0.000001140, "power": 0.397
    },
    "Ethash":
    {
      "bin": "/home/m1/NVOC/mining/miners/ethminer/latest/ethminer -S {HOST}:{PORT} -O {NAME}.{MINER}:x -U",
      "power_limit": 100, "gpu_oc": 100, "mem_oc": 100, "fan": 0,
      "speed": 0.087, "power": 0.397
    },
    "Groestl":
    {
      "bin": "/home/m1/NVOC/mining/miners/SPccminer/ccminer -a groestl -o stratum+tcp://{HOST}:{PORT} -u {NAME}.{MINER} -p x",
      "power_limit": 100, "gpu_oc": 100, "mem_oc": 100, "fan": 0,
      "speed": 0.0853, "power": 0.392
    },
    "Keccak":
    {
      "bin": "/home/m1/NVOC/mining/miners/SPccminer/ccminer -a keccak -o stratum+tcp://{HOST}:{PORT} -u {NAME}.{MINER} -p x",
      "power_limit": 100, "gpu_oc": 100, "mem_oc": 100, "fan": 0,
      "speed": 1.45, "power": 0.391
    },
    "Lyra2RE2":
    {
      "bin": "/home/m1/NVOC/mining/miners//SPccminer/ccminer -a lyra2v2 -o stratum+tcp://{HOST}:{PORT} -u {NAME}.{MINER} -p x",
      "power_limit": 100, "gpu_oc": 100, "mem_oc": 100, "fan": 0,
      "speed": 0.081, "power": 0.386
    },
    "Myriad-Groestl":
    {
      "bin": "/home/m1/NVOC/mining/miners/SPccminer/ccminer -a myr-gr -o stratum+tcp://{HOST}:{PORT} -u {NAME}.{MINER} -p x",
      "power_limit": 100, "gpu_oc": 100, "mem_oc": 100, "fan": 0,
      "speed": 0.158, "power": 0.391
    },
    "NeoScrypt":
    {
      "bin": "/home/m1/NVOC/mining/miners/KTccminer/ccminer -a neoscrypt -o stratum+tcp://{HOST}:{PORT} -u {NAME}.{MINER} -p x",
      "power_limit": 100, "gpu_oc": 100, "mem_oc": 100, "fan": 0,
      "speed": 0.002160, "power": 0.397
    },
    "Qubit":
    {
      "bin": "/home/m1/NVOC/mining/miners/SPccminer/ccminer -a qubit -o stratum+tcp://{HOST}:{PORT} -u {NAME}.{MINER} -p x",
      "power_limit": 100, "gpu_oc": 100, "mem_oc": 100, "fan": 0,
      "speed": 0.0509, "power": 0.382
    },
    "Scrypt":
    {
      "bin": "/home/m1/NVOC/mining/miners/SPccminer/ccminer -a scrypt -o stratum+tcp://{HOST}:{PORT} -u {NAME}.{MINER} -p x",
      "power_limit": 100, "gpu_oc": 100, "mem_oc": 100, "fan": 0,
      "speed": 0.00224, "power": 0.403
    },
    "Sia":
    {
      "bin": "/home/m1/NVOC/mining/miners/SPccminer/ccminer -a sia -o stratum+tcp://{HOST}:{PORT} -u {NAME}.{MINER} -p x",
      "power_limit": 100, "gpu_oc": 100, "mem_oc": 100, "fan": 0,
      "speed": 3.700, "power": 0.403
    },
    "Skein":
    {
      "bin": "/home/m1/NVOC/mining/miners/ASccminer/ccminer -a skein -o stratum+tcp://{HOST}:{PORT} -u {NAME}.{MINER} -p x",
      "power_limit": 100, "gpu_oc": 100, "mem_oc": 100, "fan": 0,
      "speed": 0.835, "power": 0.383
    },
    "X11":
    {
      "bin": "/home/m1/NVOC/mining/miners/TPccminer/ccminer -a x11 -o stratum+tcp://{HOST}:{PORT} -u {NAME}.{MINER} -p x",
      "power_limit": 100, "gpu_oc": 100, "mem_oc": 100, "fan": 0,
      "speed": 0.0327, "power": 0.403
    }
  }
}
its trying to mine CRYPRONIGHTHEAVY with xmr-stak But its not refrenced in either the mph_conf.json file  i did this on a fresh copy of the latest download image than  burned to HDD than nvOC update
i have to take brake for the night but if no one is able to look at it by morning i will attempt a fix for it in the morning but i would not hold your breath


/home/m1/NVOC/mining/2unix: line 48:  9477 Terminated              bash "${NVOC}/3main"
/home/m1/NVOC/mining/1bash: line 373: CRYPTONIGHTHEAVY: command not found
/home/m1/NVOC/mining/1bash: line 373: CRYPTONIGHTHEAVY: command not found

**Comment by snippy62** [comment]
@LuKePicci i was playing with that install and broke it so had to start fresh i think i got it This is a new fresh install downloaded than burned on to a hdd than ran nvOC upgrade 
its trying to mine
ALGO ......................: CRYPTONIGHTHEAVY
but i cant find it located in my mph_conf.json 

      Report generator v0019-2.1.0012 by leenoox      


[code]

Software info:
Report ver    :  v0019-2.1.0012
nvOC path     :  /home/m1/NVOC/mining
nvOC (1bash)  :  nvOC v0019-2.1 - Community Release
nvOC (3main)  :  nvOC v0019-2.1 - Community Release   
1bash ver     :  v0019-2.1.0031
3main ver     :  v0019-2.1.0024                  
5watchdog ver :  v0019-2.1.020   
6tempcontrol v:  v0019-2.1.0006   
wtm switch ver:  v0019-2.1.0022   
Kernel        :  4.4.0-130-generic
OS            :  Ubuntu 16.04.4 LTS
System        :  (gcc 5.4.0 (Ubuntu 5.4.0-6ubuntu1~16.04.9)
nvidia driver :  390.67

Hardware info:
Motherboard   :  Gateway DX4840  
BIOS ver.     :  P01-A4         02/15/2011
CPU Model     :  Core(TM) i3 CPU         550  @ 3.20GHz
CPU Cores     :  4 (Cores + Threads)
Mem Total     :         3971396 kB
Mem Free      :          651148 kB
Swap Total    :               0 kB
Swap Free     :               0 kB
Ethernet      :  Realtek RTL8111/8168/8411 PCI Express Gigabit Ethernet Controller (rev 06)

CUDA SDK version
nvcc path     : /usr/local/cuda-8.0/bin/nvcc
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2016 NVIDIA Corporation
Built on Tue_Jan_10_13:22:03_CST_2017
Cuda compilation tools, release 8.0, V8.0.61

nvoc.service systemd's log
● nvoc.service - nvOC Service
   Loaded: loaded (/etc/systemd/system/nvoc.service; static; vendor preset: enabled)
   Active: inactive (dead)

HDD and Partion info:
NAME     SIZE FSTYPE TYPE ROTA HOTPLUG TRAN   VENDOR   MODEL             REV MOUNTPOINT
sda    931.5G        disk    1       0 sata   ATA      TOSHIBA MQ01ABD1 1Q   
├─sda1     9M vfat   part    1       0                                       
└─sda2 931.5G ext4   part    1       0                                       /

VGA info:
01:00.0 VGA compatible controller: NVIDIA Corporation Device 1c02 (rev a1)
03:00.0 VGA compatible controller: NVIDIA Corporation GM206 [GeForce GTX 960] (rev a1)

Local git branch and submodules status:
## release...origin/release
 M 1bash.template
 0892f996d13b17738325880af704a60cd7b4567f miners (remotes/origin/19-2.1)
## HEAD (no branch)
 cd6fab68823e247bb84dd1fa0448d5f75ec4917d ANXccminer/src (heads/master)
 aafe2d19b6d9eb07d942d70ced3049e9aed1c241 ASccminer/src (1.5.3-tpruvot-81-gaafe2d1)
 31865e0b846ad98e2ce99aeb9b28bb51d3be22db KTccminer-cryptonight/src (2.06)
 c5ab73837c8024f1e6b8fe7ad46e6881fb8366e6 KTccminer/src (1.4.6-tpruvot-1293-gc5ab738)
 7d41d49b92db27b9ab80270adaa92f6b06d1ef78 KXccminer/src (0.1)
 78dad7dd659eae72a07d2448de62b1946c1f2b41 MSFTccminer/src (2.2.5-rvn)
 8affcb9cd09edd917d33c1ed450f23400f571bdb NAccminer/src (v2.2-mod-r2)
 9e86bdd24ed7911b698f1d0ef61a4028fcbd13c5 SPccminer/src (1.5.81)
 c800f1a803e1b2074ed2a7c15023c096d0772048 SUPRminer/src (1.5)
 a81ab0f7a557a12a21d716dd03537bc8633fd176 TPccminer/src (2.2.5-tpruvot)
 bfd1c002f98f2d63f2174618838afc28cf4ffffe cpuOPT/src (v3.8.8.1)
 48b170a5828256600ca71e66d4c114af4e114236 vertminer/src (v1.0-beta.2)
 c0ab1734332d6472225d8ac7394f6fcba71aabc9 xmr-stak/src (2.4.4)

1bash settings:
1bash version .............: v0019-2.1.0031
LOCAL or REMOTE ...........: LOCAL
TEAMVIEWER started ........: YES
SSH daemon started ........: NO
SLOW_USB_KEY_MODE .........: NO
SRR .......................: NO

Watchdog ..................: YES
SYSRQ Reboot ..............: NO
Watchdog Cycle ............: 15
GPU Utilization Threshold .: 70
Alternate Pool ............: NO

Temp Control ..............: YES
MANUAL_FAN ................: NO
TARGET_TEMP ...............: 65
__FAN_ADJUST ..............: 5
POWER_ADJUST ..............: 5
ALLOWED_TEMP_DIFF .........: 2
RESTORE_POWER_LIMIT .......: 85
MINIMAL_FAN_SPEED .........: 50
MAXIMAL_FAN_SPEED .........: 95

CLEAR_LOGS_ON_BOOT ........: NO
AUTO_UPDATE ...............: STABLE
AUTO_REBOOT ...............: NO
_Parallax_MODE (upPaste)...: NO

TELEGRAM_MESSAGES .: NO
TELEGRAM_ALERTS ...: NO

HEADLESS MODE:.............: NO
GPUPowerMizerMode_Adjust...: NO
ETH Pill ..................: NO

POWERLIMIT MODE ...........: GLOBAL
Power Limit WATTS .........: 100
OVERCLOCK MODE ............: GLOBAL
Memory Overclock ..........: 100
Core Overclock ............: 100

GLOBAL WORKERNAME .........: YES
AUTO WORKERNAME ...........: CUSTOM
WORKERNAME ................: Snippy6
plusCPU ...................: NO

COIN ......................: 
ALGO ......................: CRYPTONIGHTHEAVY
MINER .....................: xmr-stak
ZPOOLPASS .................: hidden_pass...,
WORKER ................:
ADDRESS ...............: ...
POOL ..................:
PORT ..................:
CRYPTONIGHTHEAVY INTENSITY ..........: 0

[/code]


WORK IN PROGRESS! Report script (beta release)

*** If posting the Report on bitcointalk.org forum please copy everything
    between the [code] and [/code] including the [code] and [/code] tags.
    This will ensure proper alignment when posting the Report.


m1@m1-desktop:~/NVOC/mining$

**Comment by LuKePicci** [comment]
Two quick notes:
- when you burn an image it will download the latest revision from the selected branch, so if you replaced in firstboot.json  "release" with "19-2.1" it automatically installed the latest tree in "19-2.1" branch, so no need to run nvOC upgrade immediately after
- if you just want to cleanup your installation, you don't need to reimage (if you are already on the latest image) you can just delete the NVOC folder from your home directory or wherever you placed it, and select the firstboot gnome-terminal profile as default in terminal preferences, and reboot: it will run again the firstboot experience with config you have in the fat partition, so take care of placing there an updated 1bash

**Comment by snippy62** [comment]
thanks for the advice that is way easier to do it that way than what i have been doing still unable to use sulfers auto switch the only thing i can figure out is that when it tryes to launch from mph_switch there is no heavycoin info in the mph_json folder and on my generated report it says my algo ALGO ......................: CRYPTONIGHTHEAVY so im guessing there is the problem becasue when i jump over and check my glake it says there has been no file to open witch to me is because it dont know how to deal with ALGO ......................: CRYPTONIGHTHEAVY

**Comment by snippy62** [comment]
on another note why this error 
m1@m1-desktop:~$nvOC install-service
Reinstalling nvOC service for /home/m1/NVOC/mining
Setting ACL for 'nvoc' user write access to NVOC path...
setfacl: Option -m: Invalid argument near character 6
Done. This service has autostart enabled.
m1@m1-desktop:~/NVOC/mining$

**Comment by LuKePicci** [comment]
Because probably you have not created the required service user for installing nvOC as a system service, it is an alternative way of running nvOC suitable for different scenarios, if you don't need it don't care. For more info read #62 .

**Comment by LuKePicci** [comment]
CNheavy is not supported by mph_switch and mph itself,, but the switcher should avoid taking into account unconfigured algos, so I'm not sure what's wrong with it.

**Comment by LuKePicci** [comment]
@snippy62 I noticed your last test was with no COIN set, I found a bug which lead to selecting the last algo in 0algo_id when COIN was "", that's why it was trying to mine CNheavy. Actually neither mph nor the mph_witch has nothingo to do with CNheavy, the only salter-like switcher compatible with CNheavy is programatic_switch.

**Comment by snippy62** [comment]
If i selected mph_switch what should i select as the coin instead if ""

**Comment by LuKePicci** [comment]
If you select AUTO_SWITCH="SALFTER_MPH_SWITCHING" then the COIN value can be anything since it is ignored, but if you set AUTO_SWITCH="NO" or whatever is not a valid auto switcher name it will mine COIN. That's why in #146 I both took care of handling COIN="" when no valid auto switcher is selected and of adding AUTO_SWITCH variable value to nvOC report.

**Comment by LuKePicci** [comment]
Could you verify what you have set as AUTO_SWITCH value in 1bash?

**Comment by snippy62** [comment]
yes i do i did apply your changes and now its not registering properly so my glake is still showing that there is no file to open view the miner 
tail -n 0 -f /home/m1/NVOC/mining/nvoc_logs/screenlog.0
m1@m1-desktop:~$ tail -n 0 -f /home/m1/NVOC/mining/nvoc_logs/screenlog.0
tail: cannot open '/home/m1/NVOC/mining/nvoc_logs/screenlog.0' for reading: No such file or directory
tail: no files remaining
m1@m1-desktop:~$ 
the tail end of my reprot dose look better 

AUTO_SWITCH ...............: SALFTER_MPH_SWITCHING
COIN ......................: none
ALGO ......................: UNDEFINED
MINER .....................: 
none WORKER ................:
none ADDRESS ...............: ...
none POOL ..................:
also tryed to place auto_switch as the coin 


AUTO_SWITCH ...............: SALFTER_MPH_SWITCHING
COIN ......................: AUTO_SWITCH
ALGO ......................: UNDEFINED
MINER .....................: 
AUTO_SWITCH WORKER ................:
AUTO_SWITCH ADDRESS ...............: ...
AUTO_SWITCH POOL ..................:

But all times i did have Auto_SWITCH set to salfter_mph_switching but as the reprots reflect was not registering it before as it is now so its geting closer

**Comment by papampi** [comment]
What if set coin to one that is supported, likie ETH, ZEC,...

**Comment by LuKePicci** [comment]
Send here the output of gnome-terminal. The problem was there already but the issue with wrong empty coin identification was probably only affecting the report if you correctly set AUTO_SWITCH.

**Comment by snippy62** [comment]
So if i set to ZEC the tail end of the report looks like it pulling all the seting form the 1bash defalt ZEC setting witch are all valid and should start a mining process 

AUTO_SWITCH ...............: SALFTER_MPH_SWITCHING
COIN ......................: ZEC
ALGO ......................: EQUIHASH
MINER .....................: DSTM
ZEC WORKER ................: Snippy6
ZEC ADDRESS ...............: t1XfkZUZ...
ZEC POOL ..................: zec-us-east1.nanopool.org
ZEC PORT ..................: 6666

But my gnome-terminal still produces  on my AUTO_SWITCH tab
tail -n 0 -f /home/m1/NVOC/mining/nvoc_logs/screenlog.0
m1@m1-desktop:~$ tail -n 0 -f /home/m1/NVOC/mining/nvoc_logs/screenlog.0
tail: cannot open '/home/m1/NVOC/mining/nvoc_logs/screenlog.0' for reading: No such file or directory
tail: no files remaining
m1@m1-desktop:~$ 
i can confirm that that location dose not have the screenlog.0 file it dose contain 3 other files tempa , tempcontrol-screenlog.0 and watchdog-screenlog.0
Also worth mention if i set the 1bash AUTO_switch to = NO that a mining process dose start in the terminal window and a screenlog.0 file is created  i hope this helps

**Comment by papampi** [comment]
I think thats correct because salfter miners are not running in screen mode, they have their own launch sequence.
But Luca knows better how salfter switchers work ...

**Comment by papampi** [comment]
@LuKePicci 
dont we need dmSL arg in this line instead of dmS:
  subprocess.call("PATH=/usr/local/"+str(cudaVer)+"/bin:$PATH LD_LIBRARY_PATH=/usr/local/"+str(cudaVer)+"/lib64:$LD_LIBRARY_PATH screen -c "+str(outputDir)+"/nvoc_logs/screenlog.0 -dmS miner "+coin, shell=True)

And I think "-c" is to define the path to screen config file not the output log

**Comment by papampi** [comment]
May be it should be changed to:
subprocess.call("PATH=/usr/local/"+str(cudaVer)+"/bin:$PATH LD_LIBRARY_PATH=/usr/local/"+str(cudaVer)+"/lib64:$LD_LIBRARY_PATH screen -c "+str(outputDir)+"/screenrc-miner	 -dmSL miner "+coin, shell=True)

**Comment by papampi** [comment]
@snippy62 
Can you check with the last command in mph_switch file?

**Comment by snippy62** [comment]
the last line in terminal is 
31373 pts/24   S+     0:00 tail -n 0 -f /home/m1/NVOC/mining/nvoc_logs/screenlog.0
mining process in Guake Tab

if i go by watchdog GPU utilazation is 0 an both video cards for mining and will reboot loop trying to fix with no luck

OG FILE: (Showing the last 10 recorded entries)

Tue Jul 17 10:02:26 MST 2018 - Miner is running, 3main killing miner
2018-07-17 10:02:22 AM|   GPU0  72C  50% |  294.3 Sol/s   300.1 Avg   158.1 I/s | 2.65 S/W  105 W |  1.31  100  155 +
2018-07-17 10:02:22 AM|   GPU1  70C  50% |  161.1 Sol/s   161.4 Avg    86.1 I/s | 1.82 S/W   86 W |  0.60  80.0 153 
2018-07-17 10:02:22 AM|   ============== |  455.5 Sol/s   461.5 Avg   244.1 I/s | 2.24 S/W  192 W |  1.91  93.8 154
Tue Jul 17 10:05:21 MST 2018 - [CRITICAL] - Utilization is too low: reviving did not work so restarting system in 10 seconds
Tue Jul 17 10:05:31 MST 2018 - [CRITICAL] - GPU Utilization is too low: restarting 3main...
Tue Jul 17 10:07:34 MST 2018 - [WARNING] - Miner not running, reinit nvOC from scratch
Tue Jul 17 10:08:00 MST 2018 - [WARNING] - Miner not running, reinit nvOC from scratch
Tue Jul 17 10:08:26 MST 2018 - [WARNING] - Miner not running, reinit nvOC from scratch


Tue Jul 17 10:08:35 MST 2018 - [INFO] - Watchdog is starting


Tue Jul 17 10:08:37 MST 2018 - [INFO] - Installed GPUs: 2, Connected GPUs: 2

Connection to google.com 443 port [tcp/https] succeeded!
Giving miner enough to stabilize
Tue Jul 17 10:08:52 MST 2018 - [WARNING] - Miner not running, reinit nvOC from scratch

Note that when it did run until 10:02:22 AM is when i was running with Auto switch off so did not start mining

**Comment by LuKePicci** [comment]
@papampi you missed /nvoc_logs/ in the path

edit: nope, you put the config, that's right

**Comment by papampi** [comment]
It does not need nvoc_logs path in screen command, screen -c "+str(outputDir)+"/screenrc-miner is pointing to miner screen config file which it has it

**Comment by LuKePicci** [comment]
But who is executing the `tail -n 0 -f /home/m1/NVOC/mining/nvoc_logs/screenlog.0` command?

edit: got it, I was looking at the REMOTE mode code

**Comment by papampi** [comment]
Dont know who is executing that tail, but screen command should be:
screen -c Path_to_screen_config -dmSL screen-name command_to_run_in_screen

**Comment by LuKePicci** [comment]
Yes, absolutely, check if this error exists also in other salfters switchers.

**Comment by papampi** [comment]
Same bug in nice and programitic

**Comment by papampi** [comment]
@snippy62 
Can you edit mph_switch and change last line to:
subprocess.call("PATH=/usr/local/"+str(cudaVer)+"/bin:$PATH LD_LIBRARY_PATH=/usr/local/"+str(cudaVer)+"/lib64:$LD_LIBRARY_PATH screen -c "+str(outputDir)+"/screenrc-miner	-dmSL miner "+coin, shell=True)

Test and see if it works

**Comment by snippy62** [comment]
LAUNCHING:  SALFTER_MPH_SWITCHING (will launch miner)

  File "/home/m1/NVOC/mining/mph_switch", line 129
    subprocess.call("PATH=/usr/local/"+str(cudaVer)+"/bin:$PATH LD_LIBRARY_PATH=/usr/local/"+str(cudaVer)+"/lib64:$LD_LIBRARY_PATH screen -c "+str(outputDir)+"/screenrc-miner	-dmSL miner "+coin, shell=True)
                                                                                                                                                                                                             ^
IndentationError: unindent does not match any outer indentation level

**Comment by papampi** [comment]
add 2 spaces before the line:
  subprocess.call("PATH=/usr/local/"+str(cudaVer)+"/bin:$PATH LD_LIBRARY_PATH=/usr/local/"+str(cudaVer)+"/lib64:$LD_LIBRARY_PATH screen -c "+str(outputDir)+"/screenrc-miner -dmSL miner "+coin, shell=True)

**Comment by LuKePicci** [comment]
ok you have modified that line in a syntactically incorrect way, check the last commit in #146 to see how it should look

**Comment by snippy62** [comment]
IT WORKS !!!!!!!!

**Comment by snippy62** [comment]
My test rig only has 1060 3gig so its failing miner because not enough ram for the ethash but its running so i will move the changes to my other rig and test  But im able to see it running the miner 

cu  10:29:03|cuda-1  |  Set Device to current
 cu  10:29:03|cuda-0  |  Set Device to current
 cu  10:29:03|cuda-0  |  Resetting device
 cu  10:29:03|cuda-1  |  CUDA device GeForce GTX 960  has insufficient GPU memory. 2099445760  bytes of memory found < 2743073152  bytes of memory required
  ✘  10:29:04|cuda-1  |  Fatal GPU error: CUDA error in func run_ethash_search at line 60 unknown error
  ✘  10:29:04|cuda-1  |  Terminating.
  ✘  10:29:04|cuda-0  |  Fatal GPU error: CUDA error in func set_header at line 147 driver shutting down
  ✘  10:29:04|cuda-0  |  Terminating.
Warning: -S is deprecated. Use the -P parameter instead.
Warning: -O is deprecated. Use the -P parameter instead.
  m  10:29:16|ethminer|  ethminer version 0.14.0
  m  10:29:16|ethminer|  Build: linux / release +git. 24c65cf
 cu  10:29:16|ethminer|  Using grid size 8192 , block size 128
  ℹ  10:29:16|ethminer|  Selected pool us-east.ethash-hub.miningpoolhub.com:20535
  m  10:29:16|ethminer|  not-connected
  ℹ  10:29:16|stratum |  Trying 18.204.40.75:20535 ...
  ℹ  10:29:17|stratum |  Connected to us-east.ethash-hub.miningpoolhub.com  [18.204.40.75:20535]
  ℹ  10:29:17|stratum |  Spinning up miners...
  ℹ  10:29:17|cuda-0  |  No work. Pause for 3 s.
  ℹ  10:29:17|cuda-1  |  No work. Pause for 3 s.
  ℹ  10:29:17|stratum |  Subscribed to stratum server
  ℹ  10:29:17|stratum |  New pool difficulty:  4.30 gigahashes 
  ℹ  10:29:17|stratum |  New job #0e2be957…   us-east.ethash-hub.miningpoolhub.com [18.204.40.75:20535]
  ℹ  10:29:17|stratum |  Authorized worker Snippy6.Snippy6
  ℹ  10:29:20|cuda-0  |  Initialising miner 0
  ℹ  10:29:20|cuda-1  |  Initialising miner 1
  ℹ  10:29:20|stratum |  New job #2b1cb25d…   us-east.ethash-hub.miningpoolhub.com [18.204.40.75:20535]
  m  10:29:21|ethminer|  Speed   0.00 Mh/s    gpu/0  0.00  gpu/1  0.00  [A0+0:R0+0:F0] Time: 00:00
  m  10:29:26|ethminer|  Speed   0.00 Mh/s    gpu/0  0.00  gpu/1  0.00  [A0+0:R0+0:F0] Time: 00:00
 cu  10:29:28|cuda-0  |  Using device: GeForce GTX 1060 3GB  (Compute 6.1)
 cu  10:29:28|cuda-1  |  Using device: GeForce GTX 960  (Compute 5.2)
 cu  10:29:28|cuda-1  |  Set Device to current
 cu  10:29:28|cuda-0  |  Set Device to current
 cu  10:29:28|cuda-0  |  Resetting device

**Comment by snippy62** [comment]
just want to say thank @LuKePicci and @papampi  i feel like this is a great acomplishment for  me ive been trying to get this to work for ever and not really knowing anything i have lurned so much Thanks
