### ISSUE TITLE
Problem with SPECIFIC_OC by algo

### ISSUE THREAD

**Issue by cartesien** [papampi/nvOC_by_fullzero#5]
I have problems with Powerlimit settings : 

i will repost that i posted to you on BTcTalk and discord : 

BTCTalk : 

Neoscrypts overclocks settings are not correct, but i'm unable to understand where. It assign 78 instead of 120 on Powerlimit. Can you help me to fix this pb.
--
Discord : 
I observed that powerlimit for neoscrypt is 78 in the logs and in 3main starting console. Exactly what you use for skunk in specific algo for your 1060s. 
Can you correct this because i'm not familiar with your scripts and leenoox or others scripts 

Refomulate : 
 I'd look on logs to see this pb, and i know my two GTX1070s Cards can mine more than 1100 MH/s with more powerlimit of 120, but i see 78w instead of 120 that i define in 1bash.
I searched this PL in 1bash and find this is your skunk OC settings that was applied.

I read the scripts but i'm not quite familiar with theses new scripts.

So Where and Why ???

Otherwise, Good job for Wdog_control, autotemp_control too and the others scripts for WTM.
More efficient and more controls. Really bravo !

Pending patches

I détect a character number "5" at the end of line 657, is this normal ?

`    X11_POWERLIMIT_WATTS=$pwr_lim_daggerhashimoto5`

**Comment by leenoox** [comment]
Yes, you discovered a bug, that 5 at the end of
X11_POWERLIMIT_WATTS=$pwr_lim_daggerhashimoto5
shouldn't be there. Just delete the "5", change to
X11_POWERLIMIT_WATTS=$pwr_lim_daggerhashimoto
and save. Please post if this has resolved your problem

**Comment by cartesien** [comment]
Corrected.
But i'm not sure, that was the source of my problem with ALGO_SPECIFIC_OC. What do you think about this OC problem ?

**Comment by papampi** [comment]
Are you on v0019-2.0 ?

**Comment by cartesien** [comment]
Yes, I used your update script last night at 18:30 on my miner that was version 19-1.4.

This worked rather well but I spent a little too much time for my taste to put the 1bash complete with my address and other pools and other parameters ...

I just saw by passing on HUSH via your WTM automatic switch script that the miners seem to APPLY the specific OC parameters for the ALGO skunk to all miners and algo associated parts

I also forced the powerlimit in another console with the command
sudo nvidia-smi -pl 130,
but the leenox script for temperature control immediately detects and immediately puts back to the power limit at 126 that I had set yesterday for the neoscrypt algo ...

On the other hand, it seems that the power limit for lyra works well. I have seen since stop of NiceHash, Lyra algo is profitable again at least a few days or hours.

How do you get variables from this section in 1bash? I searched in your scripts but I can not find.

Thanks for your job and sharing it :-)

**Comment by papampi** [comment]
Yes the algo checkup and switch wasnt working as it should so I removed in latest stable,
You can download the lastest update script and run it again, it will not over write your 1bash and keep it intact.

**Comment by cartesien** [comment]
yes but it means that I am obliged to always use the same power for all Algos ????

I saw yours messages on BTTALK, i'll wait for your fix.

**Comment by papampi** [comment]
The latest update checks if ALGO_SPECIFIC_OC="NO" then it only restart miner to save time, if ALGO_SPECIFIC_OC="YES" then it restart 3main so OC settings takes effect

**Comment by cartesien** [comment]
Which script i must copy ???

Will you use github for updating scripts in the future ?

I just saw that tpccmin2.2.2 give us less hashrate for Lyra on MPH BTTALK thread. di you modify 3main an 0main and 1bash ?

**Comment by papampi** [comment]
Stubo compiled Tpruvot 2.2.3 but gives me  "illegal instructions", compiling it again to see how it goes

Wait a bit till we fix all minor bugs and issues and we announce the release soon.

**Comment by papampi** [comment]
ccminer-2.2.3-tpruvot
https://www.dropbox.com/s/5zxo2z0frrld6mn/ccminer-2.2.3-tpruvot.tar.gz
Miner shows 107 mh/s on 5x106 pool shows 90 , 
At least better than Alexis

**Comment by cartesien** [comment]
Ok, it's going to be a bit better indeed. I was at 66 MH/s I go up to 70 MH/s. now it is necessary to observe in time on the stats MPH.

Off topic: 
Have I read well the MPH thread ?
Will they ever put their interface to centralize everything instead of a pool per coin as currently?

Thanks for the compiled ccminer TPruvot 2.2.3. It works great.

**Comment by papampi** [comment]
Yup, seems we gonna have a page to show all workers and their hashrates

**Comment by papampi** [comment]
Compiling nanashi-ccminer now
will post all compiled versions to forum

**Comment by papampi** [comment]
nanashi-ccminer shows much more hash rate on both pool and miner
https://www.dropbox.com/s/tkgqsk0tyhhy7vh/nanashi-ccminer.tar.gz

**Comment by leenoox** [comment]
The TEMP_CONTROL script does not set the powerlimits. The only time it will adjust powerlimit is if it can not achieve the desired temperature and fan is at 100%, then it will reduce the powerlimit by 5 watts.

I am trying to find where this problem comes from but I will need some more input from you.
What coin were you trying to mine when this happened?
Did you by any chance had second commented out COIN line in 1bash like:
COIN="HUSH"
#COIN="SIGT"
What's the  INDIVIDUAL_POWERLIMIT set to?

**Comment by papampi** [comment]
I think that problem was with the wtm auto switch algo check, it should be fixed in latest version.
removed algo check for now

**Comment by cartesien** [comment]
Leenoox, 
I had understood the role of your script, and I add that in fact, what I wrote means that your script works perfectly well compared to what was initially defined. It's just that the value definition is not the right one because it comes from another part of the set of scripts one behind the other.

NO, i don't have another coin commeted under the principle coin.
My powerlimits ar theses : 

  # Neoscrypt
  if [ $COIN == "FTC" -o $COIN == "ORB" -o $COIN == "PXC" -o $COIN == "VIVO" -o $COIN == "TZC" ]
  then
    ALGORITHM="NEOSCRYPT"
	POWERLIMIT_WATTS=120
	__CORE_OVERCLOCK=150
	MEMORY_OVERCLOCK=0
  fi

  # Ethash
  if [ $COIN == "ETH" -o $COIN == "ETC" -o $COIN == "EXP" -o $COIN == "UBQ" -o $COIN == "MUSIC" -o $COIN == "SOIL" -o $COIN == "MPH_ETHASH" -o $COIN == "NICE_ETHASH"  -o $COIN == "PIRL"  ]
  then
    ALGORITHM="ETHASH"
	POWERLIMIT_WATTS=108
	__CORE_OVERCLOCK=100
	MEMORY_OVERCLOCK=1600
  fi

  # Equihash
  if [ $COIN == "BTG" -o $COIN == "ZEC" -o $COIN == "ZEN" -o $COIN == "HUSH" -o $COIN == "ZCL" -o $COIN == "KMD" -o $COIN == "ZPOOL_EQUIHASH" -o $COIN == "MPH_EQUIHASH" -o $COIN == "NICE_EQUIHASH" -o $COIN == "VOTE" ]
  then
    ALGORITHM="EQUIHASH"
	POWERLIMIT_WATTS=130
	__CORE_OVERCLOCK=150
	MEMORY_OVERCLOCK=1172
  fi

  # Skunk
  if [ $COIN == "SIGT" -o $COIN == "ZPOOL_SKUNK" -o $COIN="ALTCOM" ]
  then
    ALGORITHM="SKUNK"
    POWERLIMIT_WATTS=130
    __CORE_OVERCLOCK=150
    MEMORY_OVERCLOCK=1000
  fi

  # Cryptonight
  if [ $COIN == "XMR" -o $COIN == "KRB" -o $COIN == "ETN" ]
  then
    ALGORITHM="CRYPTONIGHT"
	POWERLIMIT_WATTS=108
	__CORE_OVERCLOCK=175
	MEMORY_OVERCLOCK=1250
  fi

  # lyra2vRev2
  if [ $COIN == "MONA" -o $COIN == "VTC" ]
  then
    ALGORITHM="LYRA2REV2"
	POWERLIMIT_WATTS=130
	__CORE_OVERCLOCK=150
	MEMORY_OVERCLOCK=-1200
  fi

  # ZCOIN lyra2v2
  if [ $COIN == "ZCOIN" ]
  then
    ALGORITHM="LYRA2V2"
    POWERLIMIT_WATTS=100
    __CORE_OVERCLOCK=160
    MEMORY_OVERCLOCK=-1000

NB : I mine neoscrypt, equihash, and lyra2 these days. Not really eth nor skein or skunk. but I put value that I drag since the time or I used the MPH switch. That is to say since September-October approximately.

But the above values are based on the bugs I found in interpreting and retrieving these values in the right variables. Finally, the ones that I thought I understood as the good ones. But since I do not understand where the mechanism of algorithm recovery is in Papampi scripts, I may be wrong.

**Comment by cartesien** [comment]
papampi,

Is nanashi ccminer can mine all coins for better hasHrate or just for lyra and neoscrypt ?

**Comment by papampi** [comment]
@cryptatometrader44 
Have you tried latest 8wtm_auto_switch Dev version v005?
Algo check enabled again, 
So if algo is same and specific oc is yes, it only restart miner not 3main any more

**Comment by papampi** [comment]
fixed.

**Comment by cartesien** [comment]
Yes i tried it today at 14h !
I had'nt seen your questions before you post fixed.

it seems to function correctly for me

**Comment by cartesien** [comment]
I'm sorry but i think it's not solved.
Your WTM_SWITCH not permit to use specific ALGO_OC correctly.

It alwatys take the skunk values.

I think you have to make an externalize script for this function.

Perhaps it's Ok if i choose LOCAL instead of REMOTE with ALGO_SPECIFIC_OC="YES"  but i see some difference between ominer and 3min launching miners.

i Desactivate ALGO_SPECIFIC_OC for now because not normally functionnal.

**Comment by papampi** [comment]
I saw you posted some mix info on forum too 
There is NO miner config in 3main and both local and remote use 0miner 

Perhaps its best to run the update script again

**Comment by cartesien** [comment]
Exactly, I picked up bits of code to add nicehash-AGLOS in your corner selection on WTM. I did not think Nicehash would come back online someday and I had actually made the recent update to

```
nvOC_ver = "nvOC v0019-2.0 Community Release" # Do not edit this
nvOC_3main_ver = "v0019-2.0.006" # Do not edit this
```

I will correct my post hoping that it did not cause any problems to others.

**Comment by cartesien** [comment]
I put this sélection for now and these params for laucnhing all miners : 
1bash
```
POWERLIMIT="YES"      
POWERLIMIT_WATTS=135     
__CORE_OVERCLOCK=150     
MEMORY_OVERCLOCK=1164    

WTM_AUTO_SWITCH_COINS="ZEC;ZCL;ZEN;KMD;HUSH;VTC;MONA;FTC;ETH;BTG;XMR;TZC;VIVO"
```
Actually, Neoscrypt seems more porfitables than all others. Equihash seems to lose ground and nesocrypt algo coins grow like mushrooms and are still very profitable, even more profitable!
